# WARNING This file is only meant to be used for local development. It is not used in production.

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=egiraffe
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_DB=egiraffe
    # volumes:
    #   # The DB does not persist data to the host, so it is not necessary to mount a volume
    #   #  for the data directory. However, it is useful to mount a volume for the init.sql
    #   #  file, so that it is easy to make changes to the schema and have them reflected
    #   #  in the DB.
    #   - ./design/database/egiraffe-schema-generated.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 127.0.0.1:5432:5432
  #for testing Mails
  mailpit:
    image: axllent/mailpit:latest
    #image: mailhog/mailhog:latest #If I want to test the chaos monkey
    ports:
      - 127.0.0.1:1025:1025 #Fake Mailserver
      - 127.0.0.1:8025:8025 #WebUI
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False" # Disable server mode
      PGADMIN_SERVER_PORT: 5432 # Port of the PostgreSQL service
      PGADMIN_SERVER_USER: "egiraffe" # PostgreSQL username
      PGADMIN_SERVER_PASSWORD: "hunter2" # PostgreSQL password
      PGADMIN_SERVER_DB: "egiraffe" # Default database
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Default email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # Default password for pgAdmin
    ports:
      - "8049:80" # Access pgAdmin at http://localhost:8049

#
#
# WARNING Again, do not use this file in production. It is only meant for local development.
#
# WARNING Again 2, do not use this file in production. It is only meant for local development.
#
