# WARNING This file is only meant to be used for local development. It is not used in production.

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=egiraffe
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_DB=egiraffe
    # volumes:
    #   # The DB does not persist data to the host, so it is not necessary to mount a volume
    #   #  for the data directory. However, it is useful to mount a volume for the init.sql
    #   #  file, so that it is easy to make changes to the schema and have them reflected
    #   #  in the DB.
    #   - ./design/database/egiraffe-schema-generated.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
    network_mode: host # hmmmmm.... Published ports are discarded when using host network mode
#
#
# WARNING Again, do not use this file in production. It is only meant for local development.
#
# Use
# export DATABASE_URL='postgresql://egiraffe:hunter2@localhost:5432/egiraffe?sslmode=disable'
# to connect to the database from the host machine, then
# cargo run
# (in the backend directory) to start the server.
#
# WARNING Again 2, do not use this file in production. It is only meant for local development.
#
